const globals = {
  urls: {
    cors: 'https://arcane-thicket-21938.herokuapp.com/',
    api: 'http://www.dnd5eapi.co/api/',
    races: {
      'Dwarf': 'http://www.dnd5eapi.co/api/races/1',
      'Elf': 'http://www.dnd5eapi.co/api/races/2',
      'Halfling': 'http://www.dnd5eapi.co/api/races/3',
      'Human': 'http://www.dnd5eapi.co/api/races/4',
      'Dragonborn': 'http://www.dnd5eapi.co/api/races/5',
      'Gnome': 'http://www.dnd5eapi.co/api/races/6',
      'Half Elf': 'http://www.dnd5eapi.co/api/races/7',
      'Half Orc': 'http://www.dnd5eapi.co/api/races/8',
      'Tiefling': 'http://www.dnd5eapi.co/api/races/9'
    },
    classes: {
      'Barbarian': 'http://www.dnd5eapi.co/api/classes/1',
      'Bard': 'http://www.dnd5eapi.co/api/classes/2',
      'Cleric': 'http://www.dnd5eapi.co/api/classes/3',
      'Druid': 'http://www.dnd5eapi.co/api/classes/4',
      'Fighter': 'http://www.dnd5eapi.co/api/classes/5',
      'Monk': 'http://www.dnd5eapi.co/api/classes/6',
      'Paladin': 'http://www.dnd5eapi.co/api/classes/7',
      'Ranger': 'http://www.dnd5eapi.co/api/classes/8',
      'Rogue': 'http://www.dnd5eapi.co/api/classes/9',
      'Sorcerer': 'http://www.dnd5eapi.co/api/classes/10',
      'Warlock': 'http://www.dnd5eapi.co/api/classes/11',
      'Wizard': 'http://www.dnd5eapi.co/api/classes/12'
    },
    spells: {
      'Acid Arrow': 'http://www.dnd5eapi.co/api/spells/1',
      'Acid Splash': 'http://www.dnd5eapi.co/api/spells/2',
      'Aid': 'http://www.dnd5eapi.co/api/spells/3',
      'Alarm': 'http://www.dnd5eapi.co/api/spells/4',
      'Alter Self': 'http://www.dnd5eapi.co/api/spells/5',
      'Animal Friendship': 'http://www.dnd5eapi.co/api/spells/6',
      'Animal Messenger': 'http://www.dnd5eapi.co/api/spells/7',
      'Animal Shapes': 'http://www.dnd5eapi.co/api/spells/8',
      'Animate Dead': 'http://www.dnd5eapi.co/api/spells/9',
      'Animate Objects': 'http://www.dnd5eapi.co/api/spells/10',
      'Antilife Shell': 'http://www.dnd5eapi.co/api/spells/11',
      'Antimagic Field': 'http://www.dnd5eapi.co/api/spells/12',
      'Antipathy/Sympathy': 'http://www.dnd5eapi.co/api/spells/13',
      'Arcane Eye': 'http://www.dnd5eapi.co/api/spells/14',
      'Arcane Hand': 'http://www.dnd5eapi.co/api/spells/15',
      'Arcane Lock': 'http://www.dnd5eapi.co/api/spells/16',
      'Arcane Sword': 'http://www.dnd5eapi.co/api/spells/17',
      'Arcanist\'s Magic Aura': 'http://www.dnd5eapi.co/api/spells/18',
      'Astral Projection': 'http://www.dnd5eapi.co/api/spells/19',
      'Augury': 'http://www.dnd5eapi.co/api/spells/20',
      'Awaken': 'http://www.dnd5eapi.co/api/spells/21',
      'Bane': 'http://www.dnd5eapi.co/api/spells/22',
      'Banishment': 'http://www.dnd5eapi.co/api/spells/23',
      'Barkskin': 'http://www.dnd5eapi.co/api/spells/24',
      'Beacon of Hope': 'http://www.dnd5eapi.co/api/spells/25',
      'Bestow Curse': 'http://www.dnd5eapi.co/api/spells/26',
      'Black Tentacles': 'http://www.dnd5eapi.co/api/spells/27',
      'Blade Barrier': 'http://www.dnd5eapi.co/api/spells/28',
      'Bless': 'http://www.dnd5eapi.co/api/spells/29',
      'Blight': 'http://www.dnd5eapi.co/api/spells/30',
      'Blindness/Deafness': 'http://www.dnd5eapi.co/api/spells/31',
      'Blink': 'http://www.dnd5eapi.co/api/spells/32',
      'Blur': 'http://www.dnd5eapi.co/api/spells/33',
      'Branding Smite': 'http://www.dnd5eapi.co/api/spells/34',
      'Burning Hands': 'http://www.dnd5eapi.co/api/spells/35',
      'Call Lightning': 'http://www.dnd5eapi.co/api/spells/36',
      'Calm Emotions': 'http://www.dnd5eapi.co/api/spells/37',
      'Chain Lightning': 'http://www.dnd5eapi.co/api/spells/38',
      'Charm Person': 'http://www.dnd5eapi.co/api/spells/39',
      'Chill Touch': 'http://www.dnd5eapi.co/api/spells/40',
      'Circle of Death': 'http://www.dnd5eapi.co/api/spells/41',
      'Clairvoyance': 'http://www.dnd5eapi.co/api/spells/42',
      'Clone': 'http://www.dnd5eapi.co/api/spells/43',
      'Cloudkill': 'http://www.dnd5eapi.co/api/spells/44',
      'Color Spray': 'http://www.dnd5eapi.co/api/spells/45',
      'Command': 'http://www.dnd5eapi.co/api/spells/46',
      'Commune': 'http://www.dnd5eapi.co/api/spells/47',
      'Commune with Nature': 'http://www.dnd5eapi.co/api/spells/48',
      'Comprehend Languages': 'http://www.dnd5eapi.co/api/spells/49',
      'Compulsion': 'http://www.dnd5eapi.co/api/spells/50',
      'Cone of Cold': 'http://www.dnd5eapi.co/api/spells/51',
      'Confusion': 'http://www.dnd5eapi.co/api/spells/52',
      'Conjure Animals': 'http://www.dnd5eapi.co/api/spells/53',
      'Conjure Celestial': 'http://www.dnd5eapi.co/api/spells/54',
      'Conjure Elemental': 'http://www.dnd5eapi.co/api/spells/55',
      'Conjure Fey': 'http://www.dnd5eapi.co/api/spells/56',
      'Conjure Minor Elementals': 'http://www.dnd5eapi.co/api/spells/57',
      'Conjure Woodland Beings': 'http://www.dnd5eapi.co/api/spells/58',
      'Contact Other Plane': 'http://www.dnd5eapi.co/api/spells/59',
      'Contagion': 'http://www.dnd5eapi.co/api/spells/60',
      'Contingency': 'http://www.dnd5eapi.co/api/spells/61',
      'Continual Flame': 'http://www.dnd5eapi.co/api/spells/62',
      'Control Water': 'http://www.dnd5eapi.co/api/spells/63',
      'Control Weather': 'http://www.dnd5eapi.co/api/spells/64',
      'Counterspell': 'http://www.dnd5eapi.co/api/spells/65',
      'Create Food and Water': 'http://www.dnd5eapi.co/api/spells/66',
      'Create Undead': 'http://www.dnd5eapi.co/api/spells/67',
      'Create or Destroy Water': 'http://www.dnd5eapi.co/api/spells/68',
      'Creation': 'http://www.dnd5eapi.co/api/spells/69',
      'Cure Wounds': 'http://www.dnd5eapi.co/api/spells/70',
      'Dancing Lights': 'http://www.dnd5eapi.co/api/spells/71',
      'Darkness': 'http://www.dnd5eapi.co/api/spells/72',
      'Darkvision': 'http://www.dnd5eapi.co/api/spells/73',
      'Daylight': 'http://www.dnd5eapi.co/api/spells/74',
      'Death Ward': 'http://www.dnd5eapi.co/api/spells/75',
      'Delayed Blast Fireball': 'http://www.dnd5eapi.co/api/spells/76',
      'Demiplane': 'http://www.dnd5eapi.co/api/spells/77',
      'Detect Evil and Good': 'http://www.dnd5eapi.co/api/spells/78',
      'Detect Magic': 'http://www.dnd5eapi.co/api/spells/79',
      'Detect Poison and Disease': 'http://www.dnd5eapi.co/api/spells/80',
      'Detect Thoughts': 'http://www.dnd5eapi.co/api/spells/81',
      'Dimension Door': 'http://www.dnd5eapi.co/api/spells/82',
      'Disguise Self': 'http://www.dnd5eapi.co/api/spells/83',
      'Disintegrate': 'http://www.dnd5eapi.co/api/spells/84',
      'Dispel Evil and Good': 'http://www.dnd5eapi.co/api/spells/85',
      'Dispel Magic': 'http://www.dnd5eapi.co/api/spells/86',
      'Divination': 'http://www.dnd5eapi.co/api/spells/87',
      'Divine Favor': 'http://www.dnd5eapi.co/api/spells/88',
      'Divine Word': 'http://www.dnd5eapi.co/api/spells/89',
      'Dominate Beast': 'http://www.dnd5eapi.co/api/spells/90',
      'Dominate Monster': 'http://www.dnd5eapi.co/api/spells/91',
      'Dominate Person': 'http://www.dnd5eapi.co/api/spells/92',
      'Dream': 'http://www.dnd5eapi.co/api/spells/93',
      'Druidcraft': 'http://www.dnd5eapi.co/api/spells/94',
      'Earthquake': 'http://www.dnd5eapi.co/api/spells/95',
      'Eldritch Blast': 'http://www.dnd5eapi.co/api/spells/96',
      'Enhance Ability': 'http://www.dnd5eapi.co/api/spells/97',
      'Enlarge/Reduce': 'http://www.dnd5eapi.co/api/spells/98',
      'Entangle': 'http://www.dnd5eapi.co/api/spells/99',
      'Enthrall': 'http://www.dnd5eapi.co/api/spells/100',
      'Etherealness': 'http://www.dnd5eapi.co/api/spells/101',
      'Expeditious Retreat': 'http://www.dnd5eapi.co/api/spells/102',
      'Eyebite': 'http://www.dnd5eapi.co/api/spells/103',
      'Fabricate': 'http://www.dnd5eapi.co/api/spells/104',
      'Faerie Fire': 'http://www.dnd5eapi.co/api/spells/105',
      'Faithful Hound': 'http://www.dnd5eapi.co/api/spells/106',
      'False Life': 'http://www.dnd5eapi.co/api/spells/107',
      'Fear': 'http://www.dnd5eapi.co/api/spells/108',
      'Feather Fall': 'http://www.dnd5eapi.co/api/spells/109',
      'Feeblemind': 'http://www.dnd5eapi.co/api/spells/110',
      'Find Familiar': 'http://www.dnd5eapi.co/api/spells/111',
      'Find Steed': 'http://www.dnd5eapi.co/api/spells/112',
      'Find Traps': 'http://www.dnd5eapi.co/api/spells/113',
      'Find the Path': 'http://www.dnd5eapi.co/api/spells/114',
      'Finger of Death': 'http://www.dnd5eapi.co/api/spells/115',
      'Fire Bolt': 'http://www.dnd5eapi.co/api/spells/116',
      'Fire Shield': 'http://www.dnd5eapi.co/api/spells/117',
      'Fire Storm': 'http://www.dnd5eapi.co/api/spells/118',
      'Fireball': 'http://www.dnd5eapi.co/api/spells/119',
      'Flame Blade': 'http://www.dnd5eapi.co/api/spells/120',
      'Flame Strike': 'http://www.dnd5eapi.co/api/spells/121',
      'Flaming Sphere': 'http://www.dnd5eapi.co/api/spells/122',
      'Flesh to Stone': 'http://www.dnd5eapi.co/api/spells/123',
      'Floating Disk': 'http://www.dnd5eapi.co/api/spells/124',
      'Fly': 'http://www.dnd5eapi.co/api/spells/125',
      'Fog Cloud': 'http://www.dnd5eapi.co/api/spells/126',
      'Forbiddance': 'http://www.dnd5eapi.co/api/spells/127',
      'Forcecage': 'http://www.dnd5eapi.co/api/spells/128',
      'Foresight': 'http://www.dnd5eapi.co/api/spells/129',
      'Freedom of Movement': 'http://www.dnd5eapi.co/api/spells/130',
      'Freezing Sphere': 'http://www.dnd5eapi.co/api/spells/131',
      'Gaseous Form': 'http://www.dnd5eapi.co/api/spells/132',
      'Gate': 'http://www.dnd5eapi.co/api/spells/133',
      'Geas': 'http://www.dnd5eapi.co/api/spells/134',
      'Gentle Repose': 'http://www.dnd5eapi.co/api/spells/135',
      'Giant Insect': 'http://www.dnd5eapi.co/api/spells/136',
      'Glibness': 'http://www.dnd5eapi.co/api/spells/137',
      'Globe of Invulnerability': 'http://www.dnd5eapi.co/api/spells/138',
      'Glyph of Warding': 'http://www.dnd5eapi.co/api/spells/139',
      'Goodberry': 'http://www.dnd5eapi.co/api/spells/140',
      'Grease': 'http://www.dnd5eapi.co/api/spells/141',
      'Greater Invisibility': 'http://www.dnd5eapi.co/api/spells/142',
      'Greater Restoration': 'http://www.dnd5eapi.co/api/spells/143',
      'Guardian of Faith': 'http://www.dnd5eapi.co/api/spells/144',
      'Guards and Wards': 'http://www.dnd5eapi.co/api/spells/145',
      'Guidance': 'http://www.dnd5eapi.co/api/spells/146',
      'Guiding Bolt': 'http://www.dnd5eapi.co/api/spells/147',
      'Gust of Wind': 'http://www.dnd5eapi.co/api/spells/148',
      'Hallow': 'http://www.dnd5eapi.co/api/spells/149',
      'Hallucinatory Terrain': 'http://www.dnd5eapi.co/api/spells/150',
      'Harm': 'http://www.dnd5eapi.co/api/spells/151',
      'Haste': 'http://www.dnd5eapi.co/api/spells/152',
      'Heal': 'http://www.dnd5eapi.co/api/spells/153',
      'Healing Word': 'http://www.dnd5eapi.co/api/spells/154',
      'Heat Metal': 'http://www.dnd5eapi.co/api/spells/155',
      'Hellish Rebuke': 'http://www.dnd5eapi.co/api/spells/156',
      'Heroes\' Feast': 'http://www.dnd5eapi.co/api/spells/157',
      'Heroism': 'http://www.dnd5eapi.co/api/spells/158',
      'Hideous Laughter': 'http://www.dnd5eapi.co/api/spells/159',
      'Hold Monster': 'http://www.dnd5eapi.co/api/spells/160',
      'Hold Person': 'http://www.dnd5eapi.co/api/spells/161',
      'Holy Aura': 'http://www.dnd5eapi.co/api/spells/162',
      'Hunter\'s Mark': 'http://www.dnd5eapi.co/api/spells/163',
      'Hypnotic Pattern': 'http://www.dnd5eapi.co/api/spells/164',
      'Ice Storm': 'http://www.dnd5eapi.co/api/spells/165',
      'Identify': 'http://www.dnd5eapi.co/api/spells/166',
      'Illusory Script': 'http://www.dnd5eapi.co/api/spells/167',
      'Imprisonment': 'http://www.dnd5eapi.co/api/spells/168',
      'Incendiary Cloud': 'http://www.dnd5eapi.co/api/spells/169',
      'Inflict Wounds': 'http://www.dnd5eapi.co/api/spells/170',
      'Insect Plague': 'http://www.dnd5eapi.co/api/spells/171',
      'Instant Summons': 'http://www.dnd5eapi.co/api/spells/172',
      'Invisibility': 'http://www.dnd5eapi.co/api/spells/173',
      'Irresistible Dance': 'http://www.dnd5eapi.co/api/spells/174',
      'Jump': 'http://www.dnd5eapi.co/api/spells/175',
      'Knock': 'http://www.dnd5eapi.co/api/spells/176',
      'Legend Lore': 'http://www.dnd5eapi.co/api/spells/177',
      'Lesser Restoration': 'http://www.dnd5eapi.co/api/spells/178',
      'Levitate': 'http://www.dnd5eapi.co/api/spells/179',
      'Light': 'http://www.dnd5eapi.co/api/spells/180',
      'Lightning Bolt': 'http://www.dnd5eapi.co/api/spells/181',
      'Locate Animals or Plants': 'http://www.dnd5eapi.co/api/spells/182',
      'Locate Creature': 'http://www.dnd5eapi.co/api/spells/183',
      'Locate Object': 'http://www.dnd5eapi.co/api/spells/184',
      'Longstrider': 'http://www.dnd5eapi.co/api/spells/185',
      'Mage Armor': 'http://www.dnd5eapi.co/api/spells/186',
      'Mage Hand': 'http://www.dnd5eapi.co/api/spells/187',
      'Magic Circle': 'http://www.dnd5eapi.co/api/spells/188',
      'Magic Jar': 'http://www.dnd5eapi.co/api/spells/189',
      'Magic Missile': 'http://www.dnd5eapi.co/api/spells/190',
      'Magic Mouth': 'http://www.dnd5eapi.co/api/spells/191',
      'Magic Weapon': 'http://www.dnd5eapi.co/api/spells/192',
      'Magnificent Mansion': 'http://www.dnd5eapi.co/api/spells/193',
      'Major Image': 'http://www.dnd5eapi.co/api/spells/194',
      'Mass Cure Wounds': 'http://www.dnd5eapi.co/api/spells/195',
      'Mass Heal': 'http://www.dnd5eapi.co/api/spells/196',
      'Mass Healing Word': 'http://www.dnd5eapi.co/api/spells/197',
      'Mass Suggestion': 'http://www.dnd5eapi.co/api/spells/198',
      'Maze': 'http://www.dnd5eapi.co/api/spells/199',
      'Meld into Stone': 'http://www.dnd5eapi.co/api/spells/200',
      'Mending': 'http://www.dnd5eapi.co/api/spells/201',
      'Message': 'http://www.dnd5eapi.co/api/spells/202',
      'Meteor Swarm': 'http://www.dnd5eapi.co/api/spells/203',
      'Mind Blank': 'http://www.dnd5eapi.co/api/spells/204',
      'Minor Illusion': 'http://www.dnd5eapi.co/api/spells/205',
      'Mirage Arcane': 'http://www.dnd5eapi.co/api/spells/206',
      'Mirror Image': 'http://www.dnd5eapi.co/api/spells/207',
      'Mislead': 'http://www.dnd5eapi.co/api/spells/208',
      'Misty Step': 'http://www.dnd5eapi.co/api/spells/209',
      'Modify Memory': 'http://www.dnd5eapi.co/api/spells/210',
      'Moonbeam': 'http://www.dnd5eapi.co/api/spells/211',
      'Move Earth': 'http://www.dnd5eapi.co/api/spells/212',
      'Nondetection': 'http://www.dnd5eapi.co/api/spells/213',
      'Pass without Trace': 'http://www.dnd5eapi.co/api/spells/214',
      'Passwall': 'http://www.dnd5eapi.co/api/spells/215',
      'Phantasmal Killer': 'http://www.dnd5eapi.co/api/spells/216',
      'Phantom Steed': 'http://www.dnd5eapi.co/api/spells/217',
      'Planar Ally': 'http://www.dnd5eapi.co/api/spells/218',
      'Planar Binding': 'http://www.dnd5eapi.co/api/spells/219',
      'Plane Shift': 'http://www.dnd5eapi.co/api/spells/220',
      'Plant Growth': 'http://www.dnd5eapi.co/api/spells/221',
      'Poison Spray': 'http://www.dnd5eapi.co/api/spells/222',
      'Polymorph': 'http://www.dnd5eapi.co/api/spells/223',
      'Power Word Kill': 'http://www.dnd5eapi.co/api/spells/224',
      'Power Word Stun': 'http://www.dnd5eapi.co/api/spells/225',
      'Prayer of Healing': 'http://www.dnd5eapi.co/api/spells/226',
      'Prestidigitation': 'http://www.dnd5eapi.co/api/spells/227',
      'Prismatic Spray': 'http://www.dnd5eapi.co/api/spells/228',
      'Prismatic Wall': 'http://www.dnd5eapi.co/api/spells/229',
      'Private Sanctum': 'http://www.dnd5eapi.co/api/spells/230',
      'Produce Flame': 'http://www.dnd5eapi.co/api/spells/231',
      'Programmed Illusion': 'http://www.dnd5eapi.co/api/spells/232',
      'Project Image': 'http://www.dnd5eapi.co/api/spells/233',
      'Protection from Energy': 'http://www.dnd5eapi.co/api/spells/234',
      'Protection from Evil and Good': 'http://www.dnd5eapi.co/api/spells/235',
      'Protection from Poison': 'http://www.dnd5eapi.co/api/spells/236',
      'Purify Food and Drink': 'http://www.dnd5eapi.co/api/spells/237',
      'Raise Dead': 'http://www.dnd5eapi.co/api/spells/238',
      'Ray of Enfeeblement': 'http://www.dnd5eapi.co/api/spells/239',
      'Ray of Frost': 'http://www.dnd5eapi.co/api/spells/240',
      'Regenerate': 'http://www.dnd5eapi.co/api/spells/241',
      'Reincarnate': 'http://www.dnd5eapi.co/api/spells/242',
      'Remove Curse': 'http://www.dnd5eapi.co/api/spells/243',
      'Resilient Sphere': 'http://www.dnd5eapi.co/api/spells/244',
      'Resistance': 'http://www.dnd5eapi.co/api/spells/245',
      'Resurrection': 'http://www.dnd5eapi.co/api/spells/246',
      'Reverse Gravity': 'http://www.dnd5eapi.co/api/spells/247',
      'Revivify': 'http://www.dnd5eapi.co/api/spells/248',
      'Rope Trick': 'http://www.dnd5eapi.co/api/spells/249',
      'Sacred Flame': 'http://www.dnd5eapi.co/api/spells/250',
      'Sanctuary': 'http://www.dnd5eapi.co/api/spells/251',
      'Scorching Ray': 'http://www.dnd5eapi.co/api/spells/252',
      'Scrying': 'http://www.dnd5eapi.co/api/spells/253',
      'Secret Chest': 'http://www.dnd5eapi.co/api/spells/254',
      'See Invisibility': 'http://www.dnd5eapi.co/api/spells/255',
      'Seeming': 'http://www.dnd5eapi.co/api/spells/256',
      'Sending': 'http://www.dnd5eapi.co/api/spells/257',
      'Sequester': 'http://www.dnd5eapi.co/api/spells/258',
      'Shapechange': 'http://www.dnd5eapi.co/api/spells/259',
      'Shatter': 'http://www.dnd5eapi.co/api/spells/260',
      'Shield': 'http://www.dnd5eapi.co/api/spells/261',
      'Shield of Faith': 'http://www.dnd5eapi.co/api/spells/262',
      'Shillelagh': 'http://www.dnd5eapi.co/api/spells/263',
      'Shocking Grasp': 'http://www.dnd5eapi.co/api/spells/264',
      'Silence': 'http://www.dnd5eapi.co/api/spells/265',
      'Silent Image': 'http://www.dnd5eapi.co/api/spells/266',
      'Simulacrum': 'http://www.dnd5eapi.co/api/spells/267',
      'Sleep': 'http://www.dnd5eapi.co/api/spells/268',
      'Sleet Storm': 'http://www.dnd5eapi.co/api/spells/269',
      'Slow': 'http://www.dnd5eapi.co/api/spells/270',
      'Spare the Dying': 'http://www.dnd5eapi.co/api/spells/271',
      'Speak with Animals': 'http://www.dnd5eapi.co/api/spells/272',
      'Speak with Dead': 'http://www.dnd5eapi.co/api/spells/273',
      'Speak with Plants': 'http://www.dnd5eapi.co/api/spells/274',
      'Spider Climb': 'http://www.dnd5eapi.co/api/spells/275',
      'Spike Growth': 'http://www.dnd5eapi.co/api/spells/276',
      'Spirit Guardians': 'http://www.dnd5eapi.co/api/spells/277',
      'Spiritual Weapon': 'http://www.dnd5eapi.co/api/spells/278',
      'Stinking Cloud': 'http://www.dnd5eapi.co/api/spells/279',
      'Stone Shape': 'http://www.dnd5eapi.co/api/spells/280',
      'Stoneskin': 'http://www.dnd5eapi.co/api/spells/281',
      'Storm of Vengeance': 'http://www.dnd5eapi.co/api/spells/282',
      'Suggestion': 'http://www.dnd5eapi.co/api/spells/283',
      'Sunbeam': 'http://www.dnd5eapi.co/api/spells/284',
      'Sunburst': 'http://www.dnd5eapi.co/api/spells/285',
      'Symbol': 'http://www.dnd5eapi.co/api/spells/286',
      'Telekinesis': 'http://www.dnd5eapi.co/api/spells/287',
      'Telepathic Bond': 'http://www.dnd5eapi.co/api/spells/288',
      'Teleport': 'http://www.dnd5eapi.co/api/spells/289',
      'Teleportation Circle': 'http://www.dnd5eapi.co/api/spells/290',
      'Thaumaturgy': 'http://www.dnd5eapi.co/api/spells/291',
      'Thunderwave': 'http://www.dnd5eapi.co/api/spells/292',
      'Time Stop': 'http://www.dnd5eapi.co/api/spells/293',
      'Tiny Hut': 'http://www.dnd5eapi.co/api/spells/294',
      'Tongues': 'http://www.dnd5eapi.co/api/spells/295',
      'Transport via Plants': 'http://www.dnd5eapi.co/api/spells/296',
      'Tree Stride': 'http://www.dnd5eapi.co/api/spells/297',
      'True Polymorph': 'http://www.dnd5eapi.co/api/spells/298',
      'True Resurrection': 'http://www.dnd5eapi.co/api/spells/299',
      'True Seeing': 'http://www.dnd5eapi.co/api/spells/300',
      'True Strike': 'http://www.dnd5eapi.co/api/spells/301',
      'Unseen Servant': 'http://www.dnd5eapi.co/api/spells/302',
      'Vampiric Touch': 'http://www.dnd5eapi.co/api/spells/303',
      'Vicious Mockery': 'http://www.dnd5eapi.co/api/spells/304',
      'Wall of Fire': 'http://www.dnd5eapi.co/api/spells/305',
      'Wall of Force': 'http://www.dnd5eapi.co/api/spells/306',
      'Wall of Ice': 'http://www.dnd5eapi.co/api/spells/307',
      'Wall of Stone': 'http://www.dnd5eapi.co/api/spells/308',
      'Wall of Thorns': 'http://www.dnd5eapi.co/api/spells/309',
      'Warding Bond': 'http://www.dnd5eapi.co/api/spells/310',
      'Water Breathing': 'http://www.dnd5eapi.co/api/spells/311',
      'Water Walk': 'http://www.dnd5eapi.co/api/spells/312',
      'Web': 'http://www.dnd5eapi.co/api/spells/313',
      'Weird': 'http://www.dnd5eapi.co/api/spells/314',
      'Wind Walk': 'http://www.dnd5eapi.co/api/spells/315',
      'Wind Wall': 'http://www.dnd5eapi.co/api/spells/316',
      'Wish': 'http://www.dnd5eapi.co/api/spells/317',
      'Word of Recall': 'http://www.dnd5eapi.co/api/spells/318',
      'Zone of Truth': 'http://www.dnd5eapi.co/api/spells/319'
    }
  },
  attr: [
    'str',
    'dex',
    'con',
    'wis',
    'int',
    'cha'
  ],
  skills: [
    'Acrobatics',
    'Animal Handling',
    'Arcana',
    'Athletics',
    'Deception',
    'History',
    'Insight',
    'Intimidation',
    'Investigation',
    'Medicine',
    'Nature',
    'Perception',
    'Performance',
    'Persuasion',
    'Religion',
    'SleightOfHand',
    'Stealth',
    'Survival'
  ],
  alignments: [
    'Lawful Good',
    'Lawful Neutral',
    'Lawful Evil',
    'Neutral Good',
    'True Neutral',
    'Neutral Evil',
    'Chaotic Good',
    'Chaotic Neutral',
    'Chaotic Evil'
  ]
}

export default globals;